### ISSUE TITLE
Snygga effekter

### ISSUE THREAD

**Issue by AndreasBom** [hj222hi/RubyOnRails-1DV450#11]
Jag gillar när man markerar ett textfält och hjälptexten glider upp och lägger sig ovanför textfältet. 
Även kryssrutorna som animeras och går från en fyrkant till en bock var snygga

**Comment by Jarleborn** [comment]
Tack :) Det är gjort med ramverket Materialize(http://materializecss.com/) som jag varmt kan rekomendera. Dock så verkar det vara någon bug med deras CDN så den hittar icke fonten typ, vilket leder till lite onädiga fel i konsolen
